### Get all categories

GET http://localhost:3000/category

### Get all dinosaurs

GET http://localhost:3000/dinosaur

### Get all stats count

GET http://localhost:3000/stat-count

### Get all stats range

GET http://localhost:3000/stat-range

### Get all dinosaurs with category

GET http://localhost:3000/dinosaur-category

