### Get all categories

GET http://localhost:3000/category

### Get all dinosaurs

GET http://localhost:3000/dinosaur

### Get all stats count

GET http://localhost:3000/stat-count

### Get all stats range

GET http://localhost:3000/stat-range

### Get all dinosaurs with category

GET http://localhost:3000/dinosaur-category

### Get all price table items

GET http://localhost:3000/price-table

### Get all stat categories

GET http://localhost:3000/stat-category

### Get balance
GET http://localhost:3000/player/discord/727664382284267631/update

### Post a transfer
POST http://localhost:3000/player/transfer
Content-Type: application/json

{
  "senderId": "727664382284267631",
  "receiverId": "358220072902459395",
  "amount": 50000
}



