### Get all categories

GET http://localhost:3000/category

### Get all dinosaurs

GET http://localhost:3000/dinosaur

### Get all stats count

GET http://localhost:3000/stat-count

### Get all stats range

GET http://localhost:3000/stat-range

### Get all dinosaurs with category

GET http://localhost:3000/dinosaur-category

### Get all price table items

GET http://localhost:3000/price-table

### Get all stat categories

GET http://localhost:3000/stat-category

### Get balance
GET http://localhost:3000/player/discord/727664382284267631/update

### Get balance peido
GET http://localhost:3000/player/discord/358220072902459395/update

### Post a transfer
POST http://localhost:3000/player/transfer
Content-Type: application/json

{
  "senderId": "727664382284267631",
  "receiverId": "358220072902459395",
  "amount": 50000
}

### Get all resources
GET http://localhost:3000/resource

### Patch resource
PATCH http://localhost:3000/resource/1
Content-Type: application/json

{
  "msg_id": 100
}

### Post order
POST http://localhost:3000/order
Content-Type: application/json

{
  "player_id": 1,
  "resource_id": 1,
  "msg_id": "12345678901234567890",
  "amount": 1,
  "price": 1000,
  "total": 1000,
  "status": "pending"
}

### Get admin
GET http://localhost:3000/admin

### Patch admin
PATCH http://localhost:3000/admin/1
Content-Type: application/json

{
  "msg_id": "100"
}
