version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: achatina-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - achatina

networks:
  achatina:
    external: true